services:
  - type: web
    name: 1win-bot
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/main.py
    healthCheckPath: /health
